export const makes = [
  { id: "acura", make: "Acura", active: true },
  { id: "alfa-romeo", make: "Alfa Romeo", active: true },
  { id: "audi", make: "Audi", active: true },
  { id: "bentley", make: "Bentley", active: true },
  { id: "bmw", make: "BMW", active: true },
  { id: "buick", make: "Buick", active: true },
  { id: "cadillac", make: "Cadillac", active: true },
  { id: "chevrolet", make: "Chevrolet", active: true },
  { id: "chrysler", make: "Chrysler", active: true },
  { id: "dodge", make: "Dodge", active: true },
  { id: "ford", make: "Ford", active: true },
  { id: "genesis", make: "Genesis", active: true },
  { id: "gmc", make: "GMC", active: true },
  { id: "honda", make: "Honda", active: true },
  { id: "hyundai", make: "Hyundai", active: true },
  { id: "infiniti", make: "Infiniti", active: true },
  { id: "jeep", make: "Jeep", active: true },
  { id: "kia", make: "Kia", active: true },
  { id: "land-rover", make: "Land Rover", active: true },
  { id: "lexus", make: "Lexus", active: true },
  { id: "lincoln", make: "Lincoln", active: true },
  { id: "lucid", make: "Lucid", active: true },
  { id: "mazda", make: "Mazda", active: true },
  { id: "mercedes-amg", make: "Mercedes-AMG", active: true },
  { id: "mercedes-benz", make: "Mercedes‑Benz", active: true },
  { id: "mercedes-maybach", make: "Mercedes‑Maybach", active: true },
  { id: "mini", make: "Mini", active: true },
  { id: "mitsubishi", make: "Mitsubishi", active: true },
  { id: "nissan", make: "Nissan", active: true },
  { id: "polestar", make: "Polestar", active: true },
  { id: "porsche", make: "Porsche", active: true },
  { id: "ram", make: "Ram", active: true },
  { id: "rimac", make: "Rimac", active: true },
  { id: "rivian", make: "Rivian", active: true },
  { id: "subaru", make: "Subaru", active: true },
  { id: "tesla", make: "Tesla", active: true },
  { id: "toyota", make: "Toyota", active: true },
  { id: "vinfast", make: "VinFast", active: true },
  { id: "volkswagen", make: "Volkswagen", active: true },
  { id: "volvo", make: "Volvo", active: true },
];
