export const authors = [
  {
    id: "beth-nichols",
    firstName: "Beth",
    lastName: "Nichols",
    label: "Beth Nichols",
    initials: "BN",
    team: {
      slug: "freelance",
      label: "Freelance",
    },
    active: true,
  },
  {
    id: "drew-dorian",
    firstName: "Drew",
    lastName: "Dorian",
    label: "Drew Dorian",
    initials: "DD",
    team: {
      slug: "bg",
      label: "Buyer's Guide",
    },
    active: true,
  },
  {
    id: "joey-capparella",
    firstName: "Joey",
    lastName: "Capparella",
    label: "Joey Capparella",
    initials: "JC",
    team: {
      slug: "bg",
      label: "Buyer's Guide",
    },
    active: true,
  },
  {
    id: "andy-wendler",
    firstName: "Andy",
    lastName: "Wendler",
    label: "Andy Wendler",
    initials: "AW",
    team: {
      slug: "bg",
      label: "Buyer's Guide",
    },
    active: true,
  },
  {
    id: "austin-parsons",
    firstName: "Austin",
    lastName: "Parsons",
    label: "Austin Parsons",
    initials: "AP",
    team: {
      slug: "bg",
      label: "Buyer's Guide",
    },
    active: true,
  },
  {
    id: "joe-lorio",
    firstName: "Joe",
    lastName: "Lorio",
    label: "Joe Lorio",
    initials: "JL",
    team: {
      slug: "cd",
      label: "Car and Driver",
    },
    active: true,
  },
  {
    id: "caleb-miller",
    firstName: "Caleb",
    lastName: "Miller",
    label: "Caleb Miller",
    initials: "CM",
    team: {
      slug: "cd",
      label: "Car and Driver",
    },
    active: true,
  },
  {
    id: "jack-fitzgerald",
    firstName: "Jack",
    lastName: "Fitzgerald",
    label: "Jack Fitzgerald",
    initials: "JF",
    team: {
      slug: "cd",
      label: "Car and Driver",
    },
    active: true,
  },
  {
    id: "becca-hackett",
    firstName: "Becca",
    lastName: "Hackett",
    label: "Becca Hackett",
    initials: "BH",
    team: {
      slug: "cd",
      label: "Car and Driver",
    },
    active: true,
  },
  {
    id: "eric-stafford",
    firstName: "Eric",
    lastName: "Stafford",
    label: "Eric Stafford",
    initials: "ES",
    team: {
      slug: "cd",
      label: "Car and Driver",
    },
    active: true,
  },
  {
    id: "david-gluckman",
    firstName: "David",
    lastName: "Gluckman",
    label: "David Gluckman",
    initials: "DG",
    team: {
      slug: "freelance",
      label: "Freelance",
    },
    active: true,
  },
  {
    id: "frankie-cruz",
    firstName: "Frankie",
    lastName: "Cruz",
    label: "Frankie Cruz",
    initials: "FC",
    team: {
      slug: "bg",
      label: "Buyer's Guide",
    },
    active: false,
  },
  {
    id: "larry-printz",
    firstName: "Larry",
    lastName: "Printz",
    label: "Larry Printz",
    initials: "LP",
    team: {
      slug: "freelance",
      label: "Freelance",
    },
    active: false,
  },
];
