let today = new Date();
let tomorrow = new Date(today);
tomorrow.setDate(today.getDate() + 1);

let dd = tomorrow.getDate();
let mm = tomorrow.getMonth() + 1;
let yyyy = tomorrow.getFullYear();

let date = `${yyyy}-${mm < 10 ? "0" + mm : mm}-${dd < 10 ? "0" + dd : dd}`;

export const testDocuments = [
  {
    id: "0002",
    highPriority: false,
    createdDate: "2025-06-15T10:00:00",
    updatedDate: ["2025-06-20T12:00:00"],
    vehicle: {
      make: "Fearrari",
      model: "Roma Spider",
      segment: "Ultimate Luxury Sports Cars",
      modelYear: 2026,
    },
    author: null,
    deadline: "",
    status: "pending",
    notes: "Spider only, 2026 is final model year, replaced by Amalfi for 2027",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: false,
    new: false,
    publishedDate: "",
  },
  {
    id: "0003",
    highPriority: false,
    vehicle: {
      make: "Hyundai",
      model: "Elantra",
      segment: "Compact Cars",
      modelYear: 2026,
    },
    author: null,
    deadline: "",
    status: "pending",
    notes: "check 2026 What's New Folder",
    assets: [],
    embargoDate: "",
    embargoNotes: "Mid-July TBD",
    embargo: true,
    published: false,
    new: false,
    publishedDate: "",
  },
  {
    id: "0004",
    highPriority: true,
    vehicle: {
      make: "Rivian",
      model: "R1T",
      segment: "Electric Pickup Trucks",
      modelYear: 2026,
    },
    author: {
      id: "austin-parsons",
      firstName: "Austin",
      lastName: "Parsons",
      label: "Austin Parsons",
      initials: "AP",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: date,
    status: "pending",
    notes: "",
    assets: [
      { url: "https://imeet.com", notes: "" },
      { url: "https://caranddriver.com", notes: "" },
    ],
    embargoDate: "2025-07-08T10:00:00",
    embargoNotes: "",
    embargo: true,
    published: false,
    new: false,
    publishedDate: "",
  },
  {
    id: "0005",
    highPriority: false,
    vehicle: {
      make: "Volvo",
      model: "V60 Cross Country",
      segment: "Station Wagons",
      modelYear: 2026,
    },
    author: {
      id: "drew-dorian",
      firstName: "Drew",
      lastName: "Dorian",
      label: "Drew Dorian",
      initials: "DD",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: "2025-07-17",
    status: "rte",
    notes: "Joey reading",
    assets: [
      { url: "https://imeet.com", notes: "iMeet Link" },
      { url: "https://caranddriver.com", notes: "" },
    ],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: false,
    new: false,
    publishedDate: "",
  },
  {
    id: "0006",
    highPriority: false,
    vehicle: {
      make: "Mazda",
      model: "CX-5",
      segment: "Compact SUVs",
      modelYear: 2026,
    },
    author: {
      id: "andy-wendler",
      firstName: "Andy",
      lastName: "Wendler",
      label: "Andy Wendler",
      initials: "AW",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: "2025-07-09",
    status: "rte",
    notes: "",
    assets: [
      { url: "https://imeet.com", notes: "" },
      { url: "https://caranddriver.com", notes: "" },
    ],
    embargoDate: "2025-07-10T04:00:00",
    embargoNotes: "",
    embargo: true,
    published: false,
    new: true,
    publishedDate: "",
  },
  {
    id: "0008",
    highPriority: false,
    vehicle: {
      make: "Rivian",
      model: "R1S",
      segment: "Electric Mid-size Luxury SUVs",
      modelYear: 2026,
    },
    author: {
      id: "andy-wendler",
      firstName: "Andy",
      lastName: "Wendler",
      label: "Andy Wendler",
      initials: "AW",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: "",
    status: "scheduled",
    notes: "Scheduled for embargo time",
    assets: [],
    embargoDate: "2025-07-08T10:00:00",
    embargoNotes: "",
    embargo: true,
    published: false,
    new: false,
    publishedDate: "",
  },
  {
    id: "0009",
    highPriority: false,
    vehicle: {
      make: "Dodge",
      model: "Durango",
      segment: "Mid-size Three-row SUVs",
      modelYear: 2026,
    },
    author: {
      id: "beth-nichols",
      firstName: "Beth",
      lastName: "Nichols",
      label: "Beth Nichols",
      initials: "BN",
      team: {
        slug: "freelance",
        label: "Freelance",
        sidebar: "Freelancers",
      },
      active: true,
    },
    deadline: "",
    status: "published",
    notes: "",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: true,
    new: false,
    publishedDate: "2025-07-07T12:53:00",
  },
  {
    id: "0001",
    highPriority: false,
    vehicle: {
      make: "Audi",
      model: "A3",
      segment: "Subcompact Luxury Cars",
      modelYear: 2026,
    },
    author: {
      id: "david-gluckman",
      firstName: "David",
      lastName: "Gluckman",
      label: "David Gluckman",
      initials: "DG",
      team: {
        slug: "freelance",
        label: "Freelance",
        sidebar: "Freelancers",
      },
      active: true,
    },
    deadline: "",
    status: "pending",
    notes: "no changes expected",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: false,
    new: false,
    publishedDate: "",
  },
  {
    id: "0010",
    highPriority: false,
    vehicle: {
      make: "Acura",
      model: "TLX",
      segment: "Compact Luxury Cars",
      modelYear: 2026,
    },
    author: {
      id: "joe-lorio",
      firstName: "Joe",
      lastName: "Lorio",
      label: "Joe Lorio",
      initials: "JL",
      team: {
        slug: "cd",
        label: "Car and Driver",
        sidebar: "C/D Staff",
      },
      active: true,
    },
    deadline: "",
    status: "published",
    notes: "",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: true,
    new: false,
    publishedDate: "2025-06-29T13:01:00",
  },
  {
    id: "0011",
    highPriority: false,
    vehicle: {
      make: "GMC",
      model: "Yukon",
      segment: "Full-size SUVs",
      modelYear: 2026,
    },
    author: {
      id: "austin-parsons",
      firstName: "Austin",
      lastName: "Parsons",
      label: "Austin Parsons",
      initials: "AP",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: "",
    status: "updated",
    notes: "",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: true,
    new: true,
    publishedDate: "2025-07-01T11:11:00",
  },
  {
    id: "0007",
    highPriority: false,
    vehicle: {
      make: "Mercedes-AMG",
      model: "E53",
      segment: "Premium Sports Sedans",
      modelYear: 2026,
    },
    author: {
      id: "austin-parsons",
      firstName: "Austin",
      lastName: "Parsons",
      label: "Austin Parsons",
      initials: "AP",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: "",
    status: "rtp",
    notes: "",
    assets: [
      { url: "https://imeet.com", notes: "iMeet" },
      { url: "https://caranddriver.com", notes: "Press Release" },
    ],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: false,
    new: true,
    publishedDate: "",
  },
  {
    id: "0012",
    highPriority: false,
    vehicle: {
      make: "Acura",
      model: "TLX",
      segment: "Compact Luxury Cars",
      modelYear: 2025,
    },
    author: {
      id: "joe-lorio",
      firstName: "Joe",
      lastName: "Lorio",
      label: "Joe Lorio",
      initials: "JL",
      team: {
        slug: "cd",
        label: "Car and Driver",
        sidebar: "C/D Staff",
      },
      active: true,
    },
    deadline: "",
    status: "published",
    notes: "",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: true,
    new: false,
    publishedDate: "2025-07-19T13:01:00",
  },
  {
    id: "0013",
    highPriority: false,
    vehicle: {
      make: "GMC",
      model: "Yukon",
      segment: "Full-size SUVs",
      modelYear: 2027,
    },
    author: {
      id: "austin-parsons",
      firstName: "Austin",
      lastName: "Parsons",
      label: "Austin Parsons",
      initials: "AP",
      team: {
        slug: "bg",
        label: "Buyer's Guide",
        sidebar: "B/G Staff",
      },
      active: true,
    },
    deadline: "",
    status: "updated",
    notes: "",
    assets: [],
    embargoDate: "",
    embargoNotes: "",
    embargo: false,
    published: true,
    new: true,
    publishedDate: "2025-07-01T11:11:00",
  },
];
